export const CONTENT = {
  teleconsultingLanding: {
    name: "Teleconsulting Hero Section",
    date: "",
    description: "",
    image: "/teleconsulting_landing.png",
    perso: true,
  },
  opticianLanding: {
    name: "Optician Hero Section",
    date: "",
    description: "",
    image: "/optician_landing.png",
    perso: true,
  },
  photographeAI: {
    name: "Photographe.ai",
    date: "",
    description: "",
    image: "/photographeai_page.png",
    perso: false,
  },
  linventaire: {
    name: "L'Inventaire",
    date: "",
    description: "",
    image: "/linventaire_page.png",
    perso: false,
  },
  olky: {
    name: "Olky",
    date: "",
    description: "",
    image: "/olky_dashboard.png",
    perso: false,
  },
  luo: {
    name: "Luo",
    date: "",
    description: "",
    image: "/luo_dashboard.png",
    perso: false,
  },
  mindthreads: {
    name: "Mindthreads",
    date: "",
    description: "",
    image: "",
    perso: false,
  },
  reemployez: {
    name: "Réemployez",
    date: "",
    description: "",
    image: "/reemployez_hero.png",
    perso: false,
  },
};
